"""
models/user.py

WHY WE HAVE A USER MODEL EVEN IN GUEST MODE:
  We start with guest mode (no login required), but we still need to
  track "who" a session belongs to. We do this with a guest_id — a
  UUID string the browser generates and stores in localStorage.

  When we add real auth later, we just add email/password fields
  and the rest of the codebase doesn't need to change.

SQLMODEL TABLE CLASSES:
  When `table=True` is set, SQLModel creates a real database table.
  When `table=False` (default), it's just a Pydantic schema for validation.
  We use both:
    - table=True  → stored in SQLite (the source of truth)
    - table=False → used as request/response bodies in routes
"""

from datetime import datetime
from typing import Optional
from sqlmodel import SQLModel, Field


class GuestUser(SQLModel, table=True):
    """
    Represents a session participant.
    In guest mode: identified by UUID stored in the browser.
    In auth mode (future): will have email + hashed_password.
    """

    __tablename__ = "guest_users"

    id: Optional[int] = Field(default=None, primary_key=True)

    # UUID generated by the frontend, stored in localStorage
    # All sessions, resumes, and reports are linked to this ID
    guest_id: str = Field(unique=True, index=True)

    # Optional — populated when we add real auth later
    name: Optional[str] = Field(default=None)

    created_at: datetime = Field(default_factory=datetime.utcnow)
